In [1]:
import numpy as np

In [2]:
np.linespace(1,100,num=10)

AttributeError: module 'numpy' has no attribute 'linespace'

In [3]:
a=np.array([23,4,45,65,77,88,787,78899,3,434,5,1])
a.sort()
a

array([    1,     3,     4,     5,    23,    45,    65,    77,    88,
         434,   787, 78899])

In [4]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [5]:
np.concatenate((a,b))

array([    1,     3,     4,     5,    23,    45,    65,    77,    88,
         434,   787, 78899,     1,     2,     3,     4])

In [6]:
a=np.array([[2,3],[5,6]])
a

array([[2, 3],
       [5, 6]])

In [7]:
b=np.array([[7,9],[5,6]])
b

array([[7, 9],
       [5, 6]])

In [9]:
np.concatenate((a,b),axis=1)

array([[2, 3, 7, 9],
       [5, 6, 5, 6]])