In [3]:
import numpy as np


In [4]:
a=np.array([5,5,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
len(a)

3

In [7]:
a[0]

5

In [8]:
a[0:]

array([5, 5, 5])

In [10]:
#creating array
c=np.arange(10)
c


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
f=np.arange(1,20)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [13]:
j=np.ones(10,dtype=np.float64)
j

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])